### ISSUE TITLE
MUI url and checksum are not up-to-date

### ISSUE THREAD

**Issue by theonlydude1** [open-circle-ltd/chocolatey.adobe-acrobat-reader-dc#19]
Hello,
For the latest version of the package, the MUI url and checksum have not been updated to the proper values:
Currently:
$MUIurl = 'https://ardownload2.adobe.com/pub/adobe/reader/win/AcrobatDC/1901020064/AcroRdrDC1901020064_MUI.exe'
$MUIchecksum = '81953f3cf426cbe9e6702d1af7f727c59514c012d8d90bacfb012079c7da6d23'

Should be:
$MUIurl = 'https://ardownload2.adobe.com/pub/adobe/reader/win/AcrobatDC/2000620042/AcroRdrDC2000620042_MUI.exe'
$MUIchecksum = 'E17F6B200C1A3DA1DCAE75515F6F55A17E71D11926371B15E253A83B7BE43BBD'

The update is working fine but a fresh installation will install an old version.

**Comment by FreeMinded** [comment]
does not apply anymore
