### ISSUE TITLE
The 64 bit Adobe Reader DC is available

### ISSUE THREAD

**Issue by msoxzw** [open-circle-ltd/chocolatey.adobe-acrobat-reader-dc#23]
The base MUI is [`AcroRdrDCx642100120135_MUI.exe`](https://ardownload2.adobe.com/pub/adobe/acrobat/win/AcrobatDC/2100120135/AcroRdrDCx642100120135_MUI.exe) but without update.
The language specific base, e.g. English, is [`AcroRdrDCx642100120135_en_US.exe`](https://ardownload2.adobe.com/pub/adobe/acrobat/win/AcrobatDC/2100120135/AcroRdrDCx642100120135_en_US.exe) with latest full update [`AcroRdrDCx64Upd2100520060.msp`](https://ardownload2.adobe.com/pub/adobe/acrobat/win/AcrobatDC/2100520060/AcroRdrDCx64Upd2100520060.msp) and incremental update [`AcroRdrDCx64Upd2100520060_incr.msp`](https://ardownload2.adobe.com/pub/adobe/acrobat/win/AcrobatDC/2100520060/AcroRdrDCx64Upd2100520060_incr.msp).

Therefore, could the 64 bit Adobe Reader DC be added to this package?

**Comment by bknickelbine** [comment]
@sbaerlocher Any chance you can revisit implementing this? It's been over a year and there still isn't an option to install the 64-bit version of Adobe Reader. Thanks so much!
