### ISSUE TITLE
package name changes

### ISSUE THREAD

**Issue by conitrade-as** [open-circle-ltd/chocolatey.adobe-acrobat-reader-dc#32]
It seems that Adobe decided (besides other things) to change the installed package name. It is now displayed as `Adobe Acrobat (64-bit)` on a 64 bit machine.

As [people pointed out](https://community.chocolatey.org/packages/adobereader#comment-6163968527), this could be problematic in some situations.

Unrelated bit still good to know: Another thing we noticed is that the ProgId for file type associations changed from `AcroExch.Document.DC` to `Acrobat.Document.DC`.

**Comment by conitrade-as** [comment]
This might be related: An upgrade of the package changes the name, but stays at the same version.

After initial installation (`choco install adobereader --version=2023.001.20093 -y`):
```
Get-ItemProperty HKLM:\Software\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\* | Select-Object DisplayName, DisplayVersion, InstallDate | Where-Object { $_.DisplayName -And $_.DisplayName.StartsWith("Adobe") } | Format-Table -AutoSize

DisplayName              DisplayVersion InstallDate
-----------              -------------- -----------
Adobe Acrobat Reader MUI 23.001.20093   20230417
```

After upgrade (`choco upgrade adobereader -y`):
```
Get-ItemProperty HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall\* | Select-Object DisplayName, DisplayVersion, InstallDate | Where-Object { $_.DisplayName -And $_.DisplayName.StartsWith("Adobe") } | Format-Table -AutoSize

DisplayName            DisplayVersion InstallDate
-----------            -------------- -----------
Adobe Acrobat (64-bit) 23.001.20093   20230417
```

And a fresh installation (`choco install adobereader -y`) yields directly this outdated version:
```
Get-ItemProperty HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall\* | Select-Object DisplayName, DisplayVersion, InstallDate | Where-Object { $_.DisplayName -And $_.DisplayName.StartsWith("Adobe") } | Format-Table -AutoSize

DisplayName            DisplayVersion InstallDate
-----------            -------------- -----------
Adobe Acrobat (64-bit) 23.001.20093   20230417
```

But of course choco says this:
```
choco list -lo
adobereader 2023.001.20143
```

Platform is Windows 10 64bit Version 22H2.

**Comment by MartijnAtGithub** [comment]
Dear @sbaerlocher when can we expect a fix for this issue? Please also check the comments on https://community.chocolatey.org/packages/adobereader. Thanks thanks in advance for the feedback.

**Comment by conitrade-as** [comment]
The package has been migrated to https://github.com/pauby/chocopackages based on comments in https://github.com/open-circle-ltd/chocolatey.adobe-acrobat-reader-dc/pull/37
