### ISSUE TITLE
adobereader package does not internalize well

### ISSUE THREAD

**Issue by hackjammer** [open-circle-ltd/chocolatey.adobe-acrobat-reader-dc#9]
Business installs of chocolatey have the option to download and "internalize" the package in order to not require internet access at install time.

This functionality works by rewriting URLs it finds within the package to a local path (this part is working with the URLs that are currently embedded). As the install script has become more complex it now attempts to parse versions out of the URLs in multiple places, which fail when the URL variables are internalized:
* https://github.com/itigoag/chocolatey.adobe-acrobat-reader-dc/blob/350641e62eb0ab4414b6d1b2d190d8ff6a49bd95/adobereader/tools/chocolateyInstall.ps1#L16
* https://github.com/itigoag/chocolatey.adobe-acrobat-reader-dc/blob/350641e62eb0ab4414b6d1b2d190d8ff6a49bd95/adobereader/tools/chocolateyInstall.ps1#L29
* https://github.com/itigoag/chocolatey.adobe-acrobat-reader-dc/blob/350641e62eb0ab4414b6d1b2d190d8ff6a49bd95/adobereader/tools/chocolateyInstall.ps1#L152

Can we please update this to make it "internalizable"?

I would suggest defining the versions at the top and using them consistently throughout, including in the URLs e.g.
```
$InstallerVersion = '1901020064'
```

**Comment by sbaerlocher** [comment]
Thanks for your feedback I will look at it and if necessary also implement it,

**Comment by thoscut** [comment]
I already implemented a solution in #17. So there's the chance to remove an item from your todo just by merging the PR.

**Comment by FreeMinded** [comment]
Closing this issue as it seems to have been solved a long time with the merge of PR https://github.com/open-circle-ltd/chocolatey.adobe-acrobat-reader-dc/pull/17
